sudo: required
services:
  - docker

before_install:
  - docker build -t digsim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run digsim/react-test npm run test -- --coverage

after_success:
  - docker build -t digsim/multi-client ./client
  - docker build -t digsim/multi-nginx ./nginx
  - docker build -t digsim/multi-server ./server
  - docker build -t digsim/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push digsim/multi-client
  - docker push digsim/multi-nginx
  - docker push digsim/multi-server
  - docker push digsim/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-607205334911" # go to Services -> S3 and look for the corresponding bucket.
  bucket_path: "docker-multi"  #same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"